### PR TITLE
update to 0.12.2

### PR DESCRIPTION
**Pull request by patarapolw**
see https://community.wanikani.com/t/userscript-wanikani-jj-external-definition-from-weblio-jp-and-kanjipedia/22834/34?u=polv

### CODE REVIEW

**Comment by patarapolw** [comment]
Just in case, so that script's auto-update can be done.

**Comment by patarapolw** [comment]
If you don't feel it should be merged, or feel the repos should be separated -- feel free to close the PR without merging.

**Comment by patarapolw** [comment]
I will probably stop updating this forked repo. Updated contents are at https://github.com/patarapolw/wanikani-userscript/blob/master/userscripts/external-definition.user.js

**Comment by NicoleRauch** [comment]
Yes, sorry! I was not expecting you to make such big changes. I cannot validate those changes at a glance and don't want to put much time into checking tbh... therefore let's just keep this repo as-is. Thanks!

**Pull request closed without merging**
